# -*- coding: utf-8 -*-
"""Econ One Way ANOVA Test + Turkey HSD Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZiTuIX_OmUrSUOEmeio9Rl_3Z-lx36O
"""

"""
Economic Ideology Comparison: One-Way ANOVA + Tukey HSD (LLMs)

This script tests whether three LLMs (GPT-4, Claude, DeepSeek) differ in their
mean *economic ideology* scores across repeated trials.

Method
------
1) One-way ANOVA (SciPy):
   - Tests the null hypothesis that all group means are equal.

2) Tukey's HSD post-hoc test (statsmodels):
   - Performs pairwise comparisons between models while controlling the
     family-wise error rate (alpha = 0.05).

Notes
-----
- The score lists below should reflect the same cleaned/standardized dataset
  described in the associated paper (e.g., consistent prompts, scoring rules,
  and preprocessing).
- This file is the "economic scores" counterpart to the social-axis analysis.

Run
---
python econ_anova_tukey.py
"""

from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import numpy as np


# -------------------------------
# Input Data: Economic Scores
# -------------------------------
# Each list contains economic-axis scores from repeated trials for that model.
gpt_scores = [
    -5.25, -5.63, -6, -6.38, -6, -5.25, -5.63, -6.88, -7.5, -6.38,
    -7, -6.38, -6.5, -6.38, -6.38, -7.75, -7, -7.5, -5.88, -7,
    -3.84, -3.98, -5, -4.88, -4.88, -4.88, -4.88, -5.26, -4.88, -5.5,
    -4.88, -4.88, -4.88, -5.64, -5.38, -4.88, -5.38, -5.26, -4.62, -5.64
]

claude_scores = [
    -7.38, -5.88, -6.38, -5.88, -5.88, -5.63, -6.13, -5.88, -6.13, -6.97,
    -6.13, -7.01, -6.24, -6.86, -5.89, -6.76, -7.32, -6.55, -7.12, -6.04,
    -2.7, -2.56, -4.1, -3.98, -4.62, -3.46, -3.2, -2.94, -3.58, -3.2,
    -3.08, -3.46, -3.2, -3.84, -3.98, -3.72
]

deepseek_scores = [
    -7.13, -6.88, -6.88, -6.5, -6.5, -7.13, -7.13, -7.13, -7.13, -7.75,
    -6.38, -6.63, -7.5, -7.13, -6.88, -7.75, -6, -7.75, -7.23, -6.89,
    -5.26, -3.46, -5.9, -3.84, -3.98, -3.58, -6.92, -5, -3.08, -5.76,
    -5.76, -5.52, -5, -3.2, -3.72, -5, -5.26, -5.52, -2.56, -5.12
]


# -------------------------------
# 1) One-Way ANOVA
# -------------------------------
# Tests whether the three model groups share the same population mean.
f_stat, p_val = f_oneway(gpt_scores, claude_scores, deepseek_scores)

print("=== One-Way ANOVA (Economic Scores) ===")
print("F-statistic:", round(f_stat, 4))
print("P-value:", round(p_val, 4))

if p_val < 0.05:
    print("Result: Significant difference between group means (p < 0.05)")
else:
    print("Result: No significant difference between group means (p ≥ 0.05)")

print("--------------------------------------------")


# -------------------------------
# 2) Tukey HSD (Post-Hoc)
# -------------------------------
# Performs pairwise comparisons among models with family-wise error control.
all_scores = gpt_scores + claude_scores + deepseek_scores
labels = (
    ["GPT-4"] * len(gpt_scores) +
    ["Claude"] * len(claude_scores) +
    ["DeepSeek"] * len(deepseek_scores)
)

tukey_result = pairwise_tukeyhsd(
    endog=np.array(all_scores, dtype=float),
    groups=np.array(labels, dtype=str),
    alpha=0.05
)

print("=== Tukey HSD (pairwise comparisons) ===")
print(tukey_result)