# -*- coding: utf-8 -*-
"""Social One Way ANOVA Test + Turkey HSD Test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ev0B_3tmTWjsYBFJF6SBHYayK96n0TpE
"""

"""
ANOVA + Tukey HSD on LLM Social Ideology Scores

Purpose
-------
This script tests whether three LLMs (GPT-4, Claude, DeepSeek) differ in their
mean *social* ideology scores (e.g., libertarian/authoritarian axis after
standardization), using:

1) One-way ANOVA:
   - Tests the null hypothesis that all group means are equal.

2) Tukey's HSD (post-hoc):
   - If ANOVA suggests a significant difference, Tukey HSD identifies *which*
     pairs of groups differ while controlling family-wise error rate.

Context
-------
In the paper, the inferential pipeline is described as:
- One-Way ANOVA -> (if significant) Tukey HSD, run separately for economic and
  social scores. This file is the "social scores" version. :contentReference[oaicite:1]{index=1}

Dependencies
------------
- SciPy: f_oneway for ANOVA
- statsmodels: pairwise_tukeyhsd for Tukey HSD
- NumPy: array handling / formatting

How to run
----------
python social_anova_tukey.py
"""

from scipy.stats import f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import numpy as np


# -------------------------------
# Input Data: Social Scores
# -------------------------------
# Each list contains the social-axis scores from repeated trials of the
# political typology tests for that model.
#
# NOTE: These reflect the same cleaned/standardized dataset described in
# the methodology (e.g., after any preprocessing/outlier rules you applied).
gpt_scores = [
    -5.69, -5.49, -5.23, -5.33, -4.56, -4.67, -5.08, -5.54, -5.69, -5.33,
    -5.18, -6.31, -5.28, -6.46, -6.26, -6.41, -5.95, -6.62, -5.9, -5.95,
    -4.1, -3.87, -4.25, -4.33, -3.93, -4.45, -4.37, -3.99, -3.35, -4.46,
    -4.11, -4.06, -3.74, -3.71, -4.47, -4.01, -4.11, -4.39, -3.41, -4.17
]

claude_scores = [
    -7.03, -6.82, -6.87, -6.77, -6.26, -6.35, -5.85, -6.77, -6.67, -6.88,
    -6.15, -5.79, -6.53, -6.94, -5.47, -6.29, -5.96, -6.71, -5.38, -5.63,
    -2.11, -2.94, -3.35, -3.53, -4.04, -3.13, -2.89, -2.75, -3.21, -3.04,
    -3.03, -3.25, -3.08, -3.55, -3.63, -3.25
]

deepseek_scores = [
    -6.41, -6.1, -6, -5.74, -5.59, -6.62, -6.15, -6.1, -6.21, -6.6,
    -5.85, -5.85, -6.56, -5.49, -6.41, -6.77, -4.97, -6.15, -5.42, -6.34,
    -3.38, -3.02, -4.82, -3.19, -3.5, -2.18, -5.21, -3.51, -2.51, -4.66,
    -4.28, -4.16, -4.08, -3.74, -3.17, -3.74, -3.95, -3.92, -2.24, -3.59
]


def run_one_way_anova(*groups: list[float]) -> tuple[float, float]:
    """
    Run a one-way ANOVA across >=2 groups.

    Parameters
    ----------
    *groups : list[float]
        Each group is a list of numeric observations.

    Returns
    -------
    (f_stat, p_val) : tuple[float, float]
        F-statistic and p-value from SciPy's f_oneway.
    """
    f_stat, p_val = f_oneway(*groups)
    return float(f_stat), float(p_val)


def run_tukey_hsd(all_scores: list[float], labels: list[str], alpha: float = 0.05):
    """
    Run Tukey's Honestly Significant Difference test.

    Parameters
    ----------
    all_scores : list[float]
        Flattened observations from all groups.
    labels : list[str]
        Group label for each observation (same length as all_scores).
    alpha : float
        Significance level (default 0.05).

    Returns
    -------
    statsmodels result object (printable table)
    """
    return pairwise_tukeyhsd(
        endog=np.array(all_scores, dtype=float),
        groups=np.array(labels, dtype=str),
        alpha=alpha
    )


def main() -> None:
    """
    Execute the ANOVA + Tukey HSD workflow and print results.

    Interpretation logic:
    - If p < 0.05, reject null: at least one group mean differs.
    - Otherwise, fail to reject null: no evidence of mean differences.
    """
    # -------------------------------
    # 1) One-way ANOVA
    # -------------------------------
    f_stat, p_val = run_one_way_anova(gpt_scores, claude_scores, deepseek_scores)

    print("=== One-Way ANOVA (Social Scores) ===")
    print("F-statistic:", round(f_stat, 4))
    print("P-value:", round(p_val, 4))

    if p_val < 0.05:
        print("Result: Significant difference between group means (p < 0.05)")
    else:
        print("Result: No significant difference between group means (p ≥ 0.05)")

    print("--------------------------------------------")

    # -------------------------------
    # 2) Tukey HSD (post-hoc)
    # -------------------------------
    # Tukey is often reported after ANOVA to locate which pairs differ.
    # You can choose to only run Tukey when ANOVA is significant; here we run it
    # unconditionally for transparency (common in reporting), but you can gate it
    # behind `if p_val < 0.05:` if you prefer.
    all_scores = gpt_scores + claude_scores + deepseek_scores

    # Group labels must align 1:1 with observations.
    labels = (
        ["GPT-4"] * len(gpt_scores) +
        ["Claude"] * len(claude_scores) +
        ["DeepSeek"] * len(deepseek_scores)
    )

    tukey_result = run_tukey_hsd(all_scores, labels, alpha=0.05)

    print("=== Tukey HSD (pairwise comparisons) ===")
    print(tukey_result)


if __name__ == "__main__":
    main()