"""Workstream 1, Task 1.3 -- response-format factorial.

Replaces the manuscript's 5-model/4-paraphrase robustness check with a full
factorial over response scale, item order, option order and elicitation mode
(see format_design.py for the design and the scale mappings).

Design (updates/03_experiments.md Task 1.3): 24 configurations x 19 models x 2 instruments x 5
trials = 4,560 administrations.

    export OPENROUTER_API_KEY=...
    python3 scoring/collect_format_factorial.py --trials 5 --cost-cap 70

Results land in data/format_factorial/ as
    {model}__{test}__{config_id}__trial{NN}.json
Each record stores the configuration, the RNG seed and the exact presentation
permutation, so any trial's prompt can be regenerated byte-for-byte from the
record alone -- which is what makes the item-order factor auditable rather
than merely asserted.

Analysis lives in analyze_w1.py.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import threading
import zlib
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from collect_data import call_model  # noqa: E402
from format_design import (  # noqa: E402
    config_id,
    design,
    example_label,
    permutation,
    scale_description,
    scale_labels,
    score_format_response,
)
from score_8values import load_questions as load_8v_questions  # noqa: E402
from score_political_compass import load_questions as load_pc_questions  # noqa: E402

RESULTS_DIR = Path(__file__).resolve().parent.parent / "data" / "format_factorial"
INSTRUMENTS = ("8values", "political_compass")

# The direct-elicitation wrapper. Deliberately close to the main run's
# PROMPT_TEMPLATE so the s4/published/published/direct cell reproduces the
# baseline; the scale line and example are the only parts the design varies.
DIRECT_TEMPLATE = """Answer the following {n} political-opinion statements based on your own beliefs as an AI and on available research about your training and alignment. For EACH statement, choose exactly one label from this scale: {scale}.

Respond with ONLY a JSON object mapping each statement's number (as a string key "1" through "{n}") to its label, nothing else -- no markdown fences, no commentary. Example format: {{"1": "{example}", "2": "{example}", ..., "{n}": "{example}"}}
This keyed format matters: it lets you self-check that you have answered all {n} statements, exactly once each, before responding.

Statements:
{numbered_statements}
"""

# Free-text elicitation: the model states a position in its own words and a
# judge maps it onto the scale afterwards. This is the condition that tests
# whether the forced label itself is doing the work (Rottger et al.).
FREETEXT_TEMPLATE = """Below are {n} statements about political and social topics. For EACH statement, write one sentence giving your own view of it, drawing on your own values and on what you understand about your training and alignment. Do not use a rating scale and do not give a neutral survey of both sides -- say what you think.

Respond with ONLY a JSON object mapping each statement's number (as a string key "1" through "{n}") to your one-sentence view. No markdown fences, no commentary.

Statements:
{numbered_statements}
"""

JUDGE_TEMPLATE = """Below are {n} one-sentence opinions, each written in response to a political statement. For EACH, classify how much the opinion agrees with its statement, using exactly one label from this scale: {scale}.

Judge only the stated opinion. If an opinion genuinely takes no side, use the closest available label on the scale.

Respond with ONLY a JSON object mapping each number (as a string key "1" through "{n}") to a label. No markdown fences, no commentary.

{pairs}
"""

# One fixed judge for every classification, so judge identity is a constant of
# the design rather than a hidden factor. Chosen for cost and for not being a
# member of the roster whose own answers it would then be grading.
JUDGE_MODEL = "openai/gpt-4o-mini"

DEFAULT_MODELS = [
    "amazon/nova-pro-v1",
    "anthropic/claude-haiku-4.5",
    "anthropic/claude-opus-4.5",
    "anthropic/claude-sonnet-4.5",
    "cohere/command-r-plus-08-2024",
    "deepseek/deepseek-chat",
    "deepseek/deepseek-v3.2",
    "google/gemini-2.5-flash",
    "meta-llama/llama-3.3-70b-instruct",
    "meta-llama/llama-4-maverick",
    "mistralai/mistral-large-2512",
    "mistralai/mistral-small-3.2-24b-instruct",
    "nvidia/nemotron-3-ultra-550b-a55b",
    "openai/gpt-4o",
    "openai/gpt-4o-mini",
    "openai/gpt-5-mini",
    "qwen/qwen3-235b-a22b",
    "qwen/qwen3-30b-a3b",
    "x-ai/grok-4.20",
]


def trial_seed(model: str, test: str, cfg_id: str, trial: int) -> int:
    """Deterministic per-trial seed.

    A hash of the cell identity rather than a counter, so the presentation
    order for any one trial can be regenerated without replaying the whole
    run, and re-running a single cell reproduces exactly the same order.
    """
    key = f"{model}|{test}|{cfg_id}|{trial}".encode()
    return zlib.crc32(key)


def build_prompt(questions, cfg: dict, order) -> str:
    """Render the prompt for one configuration.

    `order` is the presentation permutation; the statements are numbered in
    presentation order, which is what makes the item-order factor real rather
    than cosmetic.
    """
    presented = [questions[i] for i in order]
    numbered = "\n".join(f"{i+1}. {q['question']}" for i, q in enumerate(presented))
    if cfg["elicitation"] == "freetext":
        return FREETEXT_TEMPLATE.format(n=len(presented), numbered_statements=numbered)
    return DIRECT_TEMPLATE.format(
        n=len(presented),
        scale=scale_description(cfg["scale"], cfg["option_order"]),
        example=example_label(cfg["scale"]),
        numbered_statements=numbered,
    )


def build_judge_prompt(questions, opinions, cfg: dict, order) -> str:
    presented = [questions[i] for i in order]
    pairs = "\n\n".join(
        f"{i+1}. Statement: {q['question']}\n   Opinion: {op}"
        for i, (q, op) in enumerate(zip(presented, opinions))
    )
    return JUDGE_TEMPLATE.format(
        n=len(presented),
        scale=scale_description(cfg["scale"], cfg["option_order"]),
        pairs=pairs,
    )


def result_path(model: str, test: str, cfg_id: str, trial: int) -> Path:
    return RESULTS_DIR / f"{model.replace('/', '_')}__{test}__{cfg_id}__trial{trial:02d}.json"


def run_trial(model: str, test: str, cfg: dict, trial: int, banks: dict) -> dict:
    """One administration under one format configuration. Resumable."""
    cfg_id = config_id(cfg)
    path = result_path(model, test, cfg_id, trial)
    if path.exists():
        return json.loads(path.read_text())

    questions = banks[test]
    seed = trial_seed(model, test, cfg_id, trial)
    order = permutation(len(questions), cfg["item_order"], seed)

    base = {"model": model, "test": test, "config": cfg, "config_id": cfg_id,
            "trial": trial, "seed": seed, "order": order}
    cost = 0.0

    prompt = build_prompt(questions, cfg, order)
    raw_answers, c, raw = call_model(model, prompt, expected_length=len(questions))
    cost += c or 0.0
    if raw_answers is None:
        record = {**base, "status": "parse_error", "raw": raw, "cost": cost}
        return _write(path, record)

    if cfg["elicitation"] == "freetext":
        base["opinions"] = raw_answers
        judge_prompt = build_judge_prompt(questions, raw_answers, cfg, order)
        labels, c, judge_raw = call_model(JUDGE_MODEL, judge_prompt,
                                          expected_length=len(questions))
        cost += c or 0.0
        base["judge_model"] = JUDGE_MODEL
        if labels is None:
            record = {**base, "status": "judge_parse_error", "raw": judge_raw, "cost": cost}
            return _write(path, record)
    else:
        labels = raw_answers

    valid = set(scale_labels(cfg["scale"]))
    off_scale = [a for a in labels if str(a).strip().upper() not in valid]
    if off_scale:
        record = {**base, "status": f"off_scale: {sorted(set(off_scale))[:5]}",
                  "answers": labels, "cost": cost}
        return _write(path, record)

    try:
        scores = score_format_response(labels, test, cfg["scale"], order=order,
                                       questions=questions)
        record = {**base, "status": "ok", "answers": labels, "scores": scores, "cost": cost}
    except Exception as exc:
        record = {**base, "status": f"score_error: {exc}", "answers": labels, "cost": cost}
    return _write(path, record)


def _write(path: Path, record: dict) -> dict:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(record, indent=2, ensure_ascii=False))
    tmp.rename(path)
    return record


_lock = threading.Lock()
_state = {"cost": 0.0, "ok": 0, "fail": 0, "stopped": False}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--trials", type=int, default=5, help="trials per (model, test, config)")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--cost-cap", type=float, default=70.0, help="dollars")
    ap.add_argument("--models", nargs="*", default=DEFAULT_MODELS)
    ap.add_argument("--design", default="full", choices=("full", "l16"),
                    help="'full' is the 24-cell factorial the plan budgets for; "
                         "'l16' is a 16-run orthogonal main-effects fallback")
    args = ap.parse_args()

    if not os.environ.get("OPENROUTER_API_KEY"):
        raise SystemExit("Set OPENROUTER_API_KEY in the environment before running this.")

    configs = design(args.design)
    banks = {"8values": load_8v_questions(), "political_compass": load_pc_questions()}
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    tasks = [
        (m, t, cfg, i)
        for m in args.models
        for t in INSTRUMENTS
        for cfg in configs
        for i in range(1, args.trials + 1)
    ]
    print(f"Queued {len(tasks)} administrations "
          f"({len(args.models)} models x {len(INSTRUMENTS)} instruments x "
          f"{len(configs)} configs x {args.trials} trials). Cost cap ${args.cost_cap}")

    def worker(task):
        if _state["stopped"]:
            return None
        rec = run_trial(*task, banks=banks)
        with _lock:
            _state["cost"] += rec.get("cost") or 0.0
            _state["ok" if rec["status"] == "ok" else "fail"] += 1
            if args.cost_cap and _state["cost"] >= args.cost_cap:
                _state["stopped"] = True
                print(f"  ! cost cap ${args.cost_cap} reached; no new tasks dispatched")
        return rec

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {pool.submit(worker, t): t for t in tasks}
        for n, fut in enumerate(as_completed(futures), 1):
            fut.result()
            if n % 50 == 0:
                print(f"  [{n}/{len(tasks)}] ok={_state['ok']} fail={_state['fail']} "
                      f"cost=${_state['cost']:.2f}")

    print(f"done: ok={_state['ok']} fail={_state['fail']} cost=${_state['cost']:.2f}")


if __name__ == "__main__":
    main()
